export default {
  UPDATE_DATE: "UPDATE_DATE",
  GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
  GET_PREMIER_MOVIES: "GET_PREMIER_MOVIES",
  GET_PREMIER_MOVIES_PENDING: "GET_PREMIER_MOVIES_PENDING",
  GET_PREMIER_MOVIES_FULFILLED: "GET_PREMIER_MOVIES_FULFILLED",
  GET_PREMIER_MOVIES_REJECTED: "GET_PREMIER_MOVIES_REJECTED",
}
