export default {
  UPDATE_DATE: "UPDATE_DATE",

  // Actions to premier movies
  GET_PREMIER_MOVIES: "GET_PREMIER_MOVIES",
  GET_PREMIER_MOVIES_PENDING: "GET_PREMIER_MOVIES_PENDING",
  GET_PREMIER_MOVIES_FULFILLED: "GET_PREMIER_MOVIES_FULFILLED",
  GET_PREMIER_MOVIES_REJECTED: "GET_PREMIER_MOVIES_REJECTED",

  // Actions to upcoming movies
  GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
  GET_UPCOMING_MOVIES_PENDING: "GET_UPCOMING_MOVIES_PENDING",
  GET_UPCOMING_MOVIES_FULFILLED: "GET_UPCOMING_MOVIES_FULFILLED",
  GET_UPCOMING_MOVIES_REJECTED: "GET_UPCOMING_MOVIES_REJECTED",

  // Actions to credits movies
  GET_CREDITS_MOVIES: "GET_CREDITS_MOVIES",
  GET_CREDITS_MOVIES_PENDING: "GET_CREDITS_MOVIES_PENDING",
  GET_CREDITS_MOVIES_FULFILLED: "GET_CREDITS_MOVIES_FULFILLED",
  GET_CREDITS_MOVIES_REJECTED: "GET_CREDITS_MOVIES_REJECTED",

  // Actions to details movies
  GET_DETAILS_MOVIES: "GET_DETAILS_MOVIES",
  GET_DETAILS_MOVIES_PENDING: "GET_DETAILS_MOVIES_PENDING",
  GET_DETAILS_MOVIES_FULFILLED: "GET_DETAILS_MOVIES_FULFILLED",
  GET_DETAILS_MOVIES_REJECTED: "GET_DETAILS_MOVIES_REJECTED",

}
